apiVersion: v1
kind: Pod
metadata:
  name: nginx # pod name
spec:
  nodeName: node01 # when creating only pod we have to set on which node to run
  containers:
  - name: nginx # container name
    image: nginx:1.14.2 # container image
    ports:
    - containerPort: 80
  tolerations: # we using this configuration to selesct on which nodes schedule our pod, the tag nodename:node-1 set on the relevant node.
  - key: "nodename"
    operator: "Equal"
    value: "node-1"
    effect: "NoSchedule"
