apiVersion: v1 ## we can use the same example for memory resources
kind: LimitRange
metadata:
  name: cpu-limit-range
spec:
  limits:
  - defualt: # limit
      cpu: 500m
    defualtRequest: # request
      cpu: 500m
    max: # limit
      cpu: "1Gi"
    min:
      cpu: 100m
    type: container