apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: akshay 
spec:
  signerName: kubernetes.io/kube-apiserver-client
  groups:
  - system:authenticated
  usages:
  - digital signature
  - key encipherment
  - server auth
  request:
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQW42ZnVkaE83WkhZODhMbkNlNVk3OHIzTU5kN0o1UnRrRGExbVBxWVlOeXhJCmppeTdGendsc3BxVmQwelZTbjhpQUV3cFVlNmU4OGZLeDBPMDFLSUJ3NE5SV0hKcHNQcEw4WERNckdqNnZhcHcKVFBmRERudjZTSmJnNkZhSVNmMzRCTTg1dFNZVmF1b1M5aHdoWTZjeVpqMjN2ZURsRGxBS1F0bGtNVGMvaEZZQwpHZVFzdkNMZDhDN3dSU0VBQWNsMmNCTnozZ3dTUE1VTDE2ZXpHRE1JRHZTUDVlelc5ci9RWlVSVVJ1bm9wR2Z6CjRIeWdqdXRmRGR5dGJTbGg2cHZvU1Rsd3ZZeDJTT3hHMnJTOGJuaTY4YjlCWmgzNTcwVzE3cTlwL0VLY3VkNHkKVW9xKzc3QTJLd0NvN0RTU3FVUkFBWHZTVXJqVkFuYVg1VnpqdnlYTlZ3SURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBRlJ5SXBIUk8xazR6UTBNR2lpSjQxRkJsb3UrZS90Uyt3NmZ5RktwQm9TT1Z2YkVhdFd2CklFMGhHY0NFQVRGTHY5Yy9oUFdvYkxnSE50L2JHSUZIU1Z1bWhWWUdaRzl0SGJXZXdEb2ZEODJFWE16UFJQUHIKRFkwcmczZ2x4SnBiUkgzTWFtWHZSblpZSHVKWVI1R01rZFRXczVBSkJDNHZKV01FejRHU3JBeURaN2d4WVRGNwo4Y3pzeStHN3REek9kN1RUdUVYbmUvRk1mRXhQN2RhL3ZyMklWZEVQR083dnZmNWg2ZU9XcWlHaStGYlVxR3dqCnFmRUczdzZ6OEd5cXdZQVJmTXdCVmlkSmxteFhveFFNcG1hbjFveU9QNmQ3UHFROU1LR1d2WnpxNE1jSjRjRGwKM2tyTmNqWFZuSWcwTENlT085Vmc4SHl1VCswNVFZWkk0ajA9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=

# to get encoded request data run: cat jane.csr | base64 

# kubectl certificate approve (request name, in this case its akshay) --- approve csr request 
# kubectl certificate deny (request name, in this case its akshay) --- deny csr request