apiVersion: v1
kind: Config
preferences: {}
clusters:
- cluster:
    certificate-authority: /etc/k8s/dev.crt
    server: https://controlplane:6443
  name: dev
- cluster:
    certificate-authority: /etc/k8s/prod.crt
    server: https://controlplane:6443
  name: prod
contexts:
- context:
    cluster: dev
    user: kubernetes-admin-dev
  name: kubernetes-admin-dev@dev
- context:
    cluster: prod
    user: kubernetes-admin-prod
  name: kubernetes-admin-prod@prod
current-context: kubernetes-admin-prod@prod
users:
- name: kubernetes-admin-dev
  user:
    client-certificate: /etc/k8s/dev_admin.crt
    client-key: /etc/k8s/dev_admin.key
- name: kubernetes-admin-prod
  user:
    client-certificate: /etc/k8s/prod_admin.crt
    client-key: /etc/k8s/prod_admin.key

# kubectl config current-context --- see current context
# kubectl config use-context (some name) --- switch context
# kubectl config use-context research --kubeconfig .kube/config2 --- use diffrent config file 