apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data: 
  DB_Host: bXlzcWw=
  DB_User: cm9vdA==
  DB_Password: cGFzd3Jk
# to encode the value from linux: echo -n 'root' | base64
# to decode the value from linux: echo -n 'bXlzcWw=' | base64 --decode